// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4fcf4dfd-5fda-47c6-89f0-d597dfbca39c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kUpfjcfRK",
    "aws_user_pools_web_client_id": "f47r2udffqpot46fbamf6v00e"
};


export default awsmobile;
